name: data
on:
  schedule:
    - cron: 5 6 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
      - name: Fetch data
        run: curl -fsSL -o tribal-leaders.csv "https://services1.arcgis.com/UxqqIfhng71wUT9x/arcgis/rest/services/TribalLeadership_Directory/FeatureServer/replicafilescache/TribalLeadership_Directory_-8807089639668789909.csv"
      - name: Run postprocess.py(clean + sort)
        run: python3 postprocess.py tribal-leaders.csv
      - name: Commit updated data
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tribal-leaders.csv
          git commit -m "Flat: latest data ($(date -u +%FT%TZ))" || exit 0
          git push
